### ISSUE TITLE
Vagrant Box

### ISSUE THREAD

**Issue by austinpray** [liveplant/liveplant-server#10]
We need to get a vagrant box up and running

https://www.vagrantup.com/

It needs to get provisioned by the golang heroku buildpack. We might need to create one.

**Comment by nathanielks** [comment]
I realized on the drive back, there _has_ to be an existing box somewhere someone has published. I'll do some looking.

**Comment by nathanielks** [comment]
Are we super tied to Vagrant? Another option is [Dokku](http://progrium.viewdocs.io/dokku/application-deployment).

**Comment by nathanielks** [comment]
Ah snap! Dokku + Vagrant: http://progrium.viewdocs.io/dokku/getting-started/install/vagrant

**Comment by nathanielks** [comment]
actually, we could do that better. alas, I am tired. I'll work on this tomorrow.
