### ISSUE TITLE
Enhance Vagrant Box

### ISSUE THREAD

**Issue by austinpray** [liveplant/liveplant-server#15]
- [x] create vagrant provisioning step
- [x] install redis and postgres by default
- [x] add https://github.com/ivpusic/go-hotreload
- [x] install [go foreman](https://github.com/liveplant/liveplant-server/issues/9) on the VM
- [x] update readme

**Comment by austinpray** [comment]
@ridhoq also wanna add what you mentioned in slack: https://github.com/ivpusic/go-hotreload

**Comment by austinpray** [comment]
Need to install foreman on the VM

**Comment by ridhoq** [comment]
Foreman or forego?

**Comment by austinpray** [comment]
https://github.com/ddollar/forego

**Comment by austinpray** [comment]
@ridhoq when you add the go-hotreload thing be sure it uses the `--debug` flag or the `LIVEPLANTDEBUG` environment variable.

**Comment by austinpray** [comment]
@ridhoq can you add vagrant instructions soon?
