### ISSUE TITLE
Verbose Mode / Configurable Logger Output

### ISSUE THREAD

**Issue by smspence** [liveplant/liveplant-server#18]
Implement logger output that can be enabled or disabled either by an argument passed to the executable at start up, or an environment variable.  The logger output would print useful debug information while the server runs and responds to requests.

For example, if debug logger is enabled, and liveplant-server receives a /votes request, it would print out information about the HTTP request (and / or current application state) to the console, and / or print out any errors or other useful debugging information.

By default, debug logger statements should be disabled.

If the liveplant server is started with argument `--debug` at the command line:

``` bash
$ liveplant-server --debug
```

then the server would subsequently run with debug logger statements enabled.

Also, if the environment variable `LIVEPLANTDEBUG=true` is present, this would also enable debug logger statements.

**Comment by austinpray** [comment]
Fixed via #20
