### ISSUE TITLE
Console idea

### ISSUE THREAD

**Issue by DarrenCattle** [liveplant/liveplant-server#3]
Basically it would be cool to have a public console for streams or events by the team. You should be able to ssh into the server and manually implement commands if necessary. That way you can ask the crowd to vote on an action and then maybe ask them what intensity they want, etc.

Forgive my psuedo code, but here's some creative stats we could consider implementing as well and maybe even showing a live feed of this console. All of these functions would relay to the Arduino for machine specific instructions. 

```
ssh admin@liveplant.io
<password>
-----------------------
//yungtom = new Plant('species','cost', 'type', 'etc');

yungtom.water(50);

Yung Tom has been watered for 50mL giving him a total of 950mL for the day since 12:00:00AM.

yungtom.nutrients(20);

Yung Tom has added 20mg of nutrients to his diet which account for 24% of his recommended daily value.

bigjohn.sunlight(15, 60);

Big John will be exposed to sunlight for the next 15 minutes at 60% intensity. This equivalent to 2 Watt-Hours of energy.
```

**Comment by DarrenCattle** [comment]
might be a little client sided but still has to have server implementability

**Comment by nathanielks** [comment]
> You should be able to ssh into the server and manually implement commands if necessary.

I'ma :-1: that pretty hardcore. Once a server is in production it shouldn't be accessible. [Security and Automation and all that](https://wblinks.com/notes/aws-tips-i-wish-id-known-before-i-started/#operations)...

> Basically it would be cool to have a public console for streams or events by the team. [...] That way you can ask the crowd to vote on an action and then maybe ask them what intensity they want, etc.

But I'ma :+1: that pretty hardcore!

> might be a little client sided but still has to have server implementability

I concur... I think we'll need a private api solely for admins for this (to mitigate point #1 above)

**Comment by nathanielks** [comment]
Oh, not to mention too, I imagine we'll be using a PaaS, so we wouldn't have SSH access anyways.

**Comment by austinpray** [comment]
> You should be able to ssh into the server and manually implement commands if necessary. 

I think you are misunderstanding what kind of server this is. This is an API server. That pseudo code you posted would have to run on a client that consumes be API. 

At this point definitely do not want to add privileged API end points because of the complexity.

**Comment by nathanielks** [comment]
:+1:
