### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by austinpray** [liveplant/liveplant-server#4]
Let's discuss where we are going to host this thing. 

I do not want this to become an exercise in hardcore devops: so I'm pretty sure I just want to host this thing on Heroku and be done with it to begin with. There is a chance this thing will go wildly viral and we will need to be able to rapidly scale. Heroku just works:tm:.

Another option would be to host on linode with our own install of http://deis.io if heroku gets too expensive. But this will steal valuable dev time from our effort.

**Comment by ridhoq** [comment]
I'm totally onboard with heroku. I can chip in if necessary. We will also want a staging environment as well.

**Comment by nathanielks** [comment]
I'm in support of heroku as well. We don't have the time to build out infrastructure.

**Comment by austinpray** [comment]
Gonna go with Heroku. Going to go ahead and put it under a free hobby plan right now.

**Comment by ridhoq** [comment]
We will also need to enable the redistogo add on as per #7

**Comment by austinpray** [comment]
We are using heroku
