### ISSUE TITLE
Start Fresh

### ISSUE THREAD

**Issue by austinpray** [liveplant/liveplant-server#5]
Let's go ahead and abandon the current dev branch that we made at HackDFW. It was a good start, but it was made under duress. I will keep the `hackdfw` branch for reference.

I'm going to 
- get us started with my general go project template 
- set up tests
- get us a simple "hello world" web app up and running
- deploy to chosen hosting (prolly gonna be heroku based on discussion in #4)

**Comment by ridhoq** [comment]
The technologies we were using at HackDFW were [codegangsta/negroni](https://github.com/codegangsta/negroni) and [gorilla/mux](https://github.com/gorilla/mux) . This is still fine with me. Do we need any libs for testing? And what about for user identification?

**Comment by austinpray** [comment]
I need to look at negroni again. Not sure about the testing situation there. 

I love using testify for go testing as well as built in test lib. 

@nathanielks had an idea for user identification at the meetup that made things p simple. What was it?

**Comment by nathanielks** [comment]
@austinpray let the browser be the user and have some sort of anti-bot verification to keep it simple.

**Comment by nathanielks** [comment]
hm... or we could at least let people input a username and if they so choose verify with an email. It could save us later in case we decide we want to track users for acheivements or _something_ requiring user tracking.

**Comment by nathanielks** [comment]
Persona is an option: https://www.mozilla.org/en-US/persona/

**Comment by austinpray** [comment]
@nathanielks persona being shut down

**Comment by nathanielks** [comment]
@austinpray aw poo.

**Comment by ridhoq** [comment]
We were actually going to use persona at hackdfw

**Comment by nathanielks** [comment]
aha! so at least on the right track

**Comment by austinpray** [comment]
Okay I'm wrong: they are not shutting it down. They are stopping active mozilla development and handing it over to the community. http://identity.mozilla.com/post/78873831485/transitioning-persona-to-community-ownership

> There are no plans to decommission Persona. If it fits your needs, please use it. We will support you.
> 
> Specifically, Mozilla staff will continue to resolve critical bugs, service disruptions, and security issues. Moreover, Mozilla’s new network operations center will handle tier 1 incident response for Persona. The center’s robust, human-backed, 24/7 monitoring will further increase Persona’s reliability and improve incident response times.

**Comment by austinpray** [comment]
I suppose this is done
